# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mysum <- function(lengthx, x, a, b, pi) {
    .Call(`_yuimaStable_mysum`, lengthx, x, a, b, pi)
}

mytail <- function(lengthx, x, exp1, V, logw) {
    .Call(`_yuimaStable_mytail`, lengthx, x, exp1, V, logw)
}

CompMatAsym <- function(pos, Deriv_A, estim_jump, logDeriv_C) {
    .Call(`_yuimaStable_CompMatAsym`, pos, Deriv_A, estim_jump, logDeriv_C)
}

CompMatAsym1 <- function(pos, Deriv_A, estim_jump, logDeriv_C, W) {
    .Call(`_yuimaStable_CompMatAsym1`, pos, Deriv_A, estim_jump, logDeriv_C, W)
}

